name: dev_mobile_avance
description: Le projet dev_mobile_avance
# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  # 🎯 CORRECTION: Mise à jour du SDK pour activer la Null Safety (Dart >= 2.12.0)
  # et être compatible avec votre version 3.8.1.
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 📦 DÉPENDANCES MANQUANTES (causes des erreurs 'uri_does_not_exist')
  firebase_core: ^2.24.2  # Assurez-vous d'utiliser la dernière version stable
  cloud_firestore: ^4.13.3 # Assurez-vous d'utiliser la dernière version stable
  image_picker: ^1.0.4    # Assurez-vous d'utiliser la dernière version stable
  
  # Autres dépendances mentionnées dans votre analyse (mettez à jour les versions si nécessaire)
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  uuid: ^4.3.1
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Outils d'analyse du code
  flutter_lints: ^3.0.1 

flutter:
  uses-material-design: true

  assets:
    # CORRECTION: Si vous utilisez cette ligne, vous devez créer le dossier 'assets/images/'
    - assets/images/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic